### ISSUE TITLE
recipe for target 'all' failed

### ISSUE THREAD

**Issue by TNMH** [SciDriver/spark-mpi#6]
I'm having trouble installing this project. These are the errors I get when executing the make-command:

```
src/pmix/CMakeFiles/pmixsrv.dir/build.make:86: recipe for target 'src/pmix/CMakeFiles/pmixsrv.dir/orterun.c.o' failed
make[2]: *** [src/pmix/CMakeFiles/pmixsrv.dir/orterun.c.o] Error 1
CMakeFiles/Makefile2:167: recipe for target 'src/pmix/CMakeFiles/pmixsrv.dir/all' failed
make[1]: *** [src/pmix/CMakeFiles/pmixsrv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea as how to solve this problem? I am using Ubuntu 16.04

Complete log file: https://gist.github.com/TNMH/33e774f82c60f1f6e859e6e8a4731aff

**Comment by malitsky** [comment]
It looks the issue is associated with the previous OpenMPI version that is located in /usr/lib/openmpi ...
In the latest version, base.h:20 uses hwloc-internal.h:

https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/base/base.h

To address this issue, I updated CMakeLists and removed a path to files associated 
with the OpenMPI installation directory.

Thank you for testing,
Nikolay

**Comment by malitsky** [comment]
It looks the issue is associated with the previous OpenMPI version that is
located in /usr/lib/openmpi ...
In the latest version, base.h:20 uses hwloc-internal.h:

https://github.com/open-mpi/ompi/blob/master/opal/mca/hwloc/base/base.h

To address this issue, I updated CMakeLists and removed a path to files
associated
with the OpenMPI installation directory.

Thank you for testing,
Nikolay

**Comment by TNMH** [comment]
Thank you for your quick reply.

Sadly, the make-command still generates an error for me:
```
(sci) tim@tim-VirtualBox:~/sci/build$ make
Scanning dependencies of target pmixsrv
[ 33%] Building C object src/pmix/CMakeFiles/pmixsrv.dir/home/tim/sci/ompi/orte/tools/orterun/main.c.o
[ 66%] Building C object src/pmix/CMakeFiles/pmixsrv.dir/orterun.c.o
make[2]: *** No rule to make target '/usr/lib/libopen-rte.so', needed by 'src/pmix/pmixsrv'.  Stop.
CMakeFiles/Makefile2:167: recipe for target 'src/pmix/CMakeFiles/pmixsrv.dir/all' failed
make[1]: *** [src/pmix/CMakeFiles/pmixsrv.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
I'm getting this error even though the source file (/usr/lib/libopen-rte.so) exists:
```
(sci) tim@tim-VirtualBox:~/sci/build$ ls /usr/lib/ | grep libopen-rte.so
libopen-rte.so
libopen-rte.so.12
libopen-rte.so.12.0.2
```
Kind regards

**Comment by malitsky** [comment]
It seems there may be some conflict with the shared libraries from the
previous MPI installation.

To avoid potential issues, I removed references to the MPI installation
directory by adding

the local MPI_SRC module associated with the MPI_SRC build directory.



The installation of the mpi4py python wrapper however requires a path to
the MPI installation directory.

Hope this helps,

Nikolay

**Comment by TNMH** [comment]
Thank you. Installation was successful.

**Comment by malitsky** [comment]
Great.
